name: workshop_template
description: Prophecy Workshop Template
version: v0.1
author: mei@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: workshop_template
  parentArtefactID: meiprophecy.io_team
  buildSystem: wheel
  author: null
  createdAt: '2023-08-14 16:54:18'
pipelines:
  pipelines/L0_bronze_ingest:
    name: L1_bronze_ingest
    description: ''
    author: mei@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-08-14 16:54:18'
    datasets:
      inputs:
      - datasets/L0_bronze_shipping_dbfs
      - datasets/L0_raw_geo_dbfs
      - datasets/L0_raw_orders_dbfs
      outputs:
      - datasets/L0_raw_geo_delta
      - datasets/L0_raw_orders_delta
      - datasets/L0_raw_shippings_delta
    subgraphs: []
    dependencies: {}
datasets:
  datasets/L0_raw_orders_dbfs:
    name: L0_orders
    description: ''
    author: mei@prophecy.io
    createdAt: '2023-08-14 17:01:21'
    mode: batch
    physicalDatasets:
      meis-metrics-test:
        fabricId: 2592
        datasetType: File
        description: ''
        author: mei@prophecy.io
        createdAt: '2023-08-14 17:01:21'
  datasets/L0_bronze_shipping_dbfs:
    name: L0_shipping
    description: ''
    author: mei@prophecy.io
    createdAt: '2023-08-14 17:02:35'
    mode: batch
    physicalDatasets:
      meis-metrics-test:
        fabricId: 2592
        datasetType: File
        description: ''
        author: mei@prophecy.io
        createdAt: '2023-08-14 17:02:35'
  datasets/L0_raw_geo_dbfs:
    name: L0_geo
    description: ''
    author: mei@prophecy.io
    createdAt: '2023-08-14 17:05:33'
    mode: batch
    physicalDatasets:
      meis-metrics-test:
        fabricId: 2592
        datasetType: File
        description: ''
        author: mei@prophecy.io
        createdAt: '2023-08-14 17:05:33'
  datasets/L0_raw_orders_delta:
    name: L1_orders_delta
    description: ''
    author: mei@prophecy.io
    createdAt: '2023-08-14 17:20:19'
    mode: batch
    physicalDatasets:
      meis-metrics-test:
        fabricId: 2592
        datasetType: Database
        description: ''
        author: mei@prophecy.io
        createdAt: '2023-08-14 17:20:19'
  datasets/L0_raw_shippings_delta:
    name: L1_shipping_delta
    description: ''
    author: mei@prophecy.io
    createdAt: '2023-08-14 17:21:53'
    mode: batch
    physicalDatasets:
      meis-metrics-test:
        fabricId: 2592
        datasetType: Database
        description: ''
        author: mei@prophecy.io
        createdAt: '2023-08-14 17:21:53'
  datasets/L0_raw_geo_delta:
    name: L1__geo_delta
    description: ''
    author: mei@prophecy.io
    createdAt: '2023-08-14 17:23:10'
    mode: batch
    physicalDatasets:
      meis-metrics-test:
        fabricId: 2592
        datasetType: Database
        description: ''
        author: mei@prophecy.io
        createdAt: '2023-08-14 17:23:10'
templates: {}
jobs: {}
functions:
  author: null
  createdAt: '2023-08-14 16:54:18'
  gems: {}
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies: {}
pipelineConfigurations: {}
